name: islieb
description: Simple reader for isLieb comics
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  firebase_messaging: ^11.3.0
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_share: ^2.0.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  provider: ^6.0.2
  url_launcher: ^6.1.2
  webfeed: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
