name: islieb
description: Simple reader for isLieb comics
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  dynamic_color: ^1.8.1
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  intl: ^0.17.0
  provider: ^6.1.5
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  webfeed: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.9.2"
  import_sorter: ^4.6.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
